export { default as TdtMap } from "./map/index.vue";
export { default as TdtMarker } from "./marker/index.vue";
export { default as TdtLabel } from "./label/index.vue";
export { default as TdtPolyline } from "./polyline/index.vue";
export { default as TdtPolygon } from "./polygon/index.vue";
export { default as TdtRectangle } from "./rectangle/index.vue";
export { default as TdtCircle } from "./circle/index.vue";
export { default as TdtInfowindow } from "./infowindow/index.vue";
export { default as TdtControl } from "./control/index.vue";
