export { default as TdtMap } from "./map/index.vue";
export { default as TdtMarker } from "./overlay/marker/index.vue";
export { default as TdtLabel } from "./overlay/label/index.vue";
export { default as TdtPolyline } from "./overlay/polyline/index.vue";
export { default as TdtPolygon } from "./overlay/polygon/index.vue";
export { default as TdtRectangle } from "./overlay/rectangle/index.vue";
export { default as TdtCircle } from "./overlay/circle/index.vue";
export { default as TdtInfowindow } from "./overlay/infowindow/index.vue";
export { default as TdtControl } from "./control/index.vue";
