name: Deply To gh-pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          yarn 
          yarn docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: docs/.vitepress/dist
