name: AutoBuild
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # - name: Install and Build
      #   run: |
      #     yarn
      #     yarn docs:build

      - name: publish
        # uses: s0/git-publish-subdir-action@master
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          repo: SoulLyoko/soullyoko.github.io
          branch: master
          dir: docs
          token: ${{ secrets.publish }}
