name: AutoBuild
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # - name: Install and Build
      #   run: |
      #     yarn
      #     yarn docs:build

      - name: publish
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:SoulLyoko/soullyoko.github.io.git
          BRANCH: master
          FOLDER: docs
          SSH_PRIVATE_KEY: ${{ secrets.publish }}
